### ISSUE TITLE
Not attribute error

### ISSUE THREAD

**Issue by Venomhash123** [AbirHasan2005/Rename-Bot#13]
Jb m upload.  As document option ko on kr deta hu to ye errors aata h

Failed to Rename File!

Error: 'NoneType' object has no attribute 'thumbs'

Traceback: Traceback (most recent call last):
  File "/app/bot/plugins/rename.py", line 93, in rename_handler
    await handle_big_rename(c, m, file_id, file_name, editable, file_type)
  File "/app/bot/core/handlers/big_rename.py", line 134, in handle_big_rename
    if m.reply_to_message.document.thumbs \
AttributeError: 'NoneType' object has no attribute 'thumbs'

**Comment by AbirHasan2005** [comment]
Send screenshot of that media which you are trying to rename.

**Comment by Venomhash123** [comment]
Maine hr video try kiya but same problem h video ka formate mkv hai
![Screenshot_2021-11-28-14-36-52-669_org telegram plus](https://user-images.githubusercontent.com/89146099/143745394-9c51a1a1-ca02-4f31-94f4-c64cf0db1cb1.png)

**Comment by AbirHasan2005** [comment]
Forward that media to https://t.me/MediasStoreBot 😅
That bot will provide you a link to the media. Post that link here. I want to check that media.

**Comment by Venomhash123** [comment]
https://t.me/MediasStoreBot?start=AbirHasan2005_NDAwNDk2

**Comment by Venomhash123** [comment]
https://t.me/MediasStoreBot?start=AbirHasan2005_NDAwNDk4

**Comment by AbirHasan2005** [comment]
You edited codes? 🤔

**Comment by Venomhash123** [comment]
Are nhi bhai tum apne aap deploy krke en video ko rename krke dekh lo 🤔🤔🤔🤔

**Comment by AbirHasan2005** [comment]
I think I have to add Force Upload Mode in this bot 🙂
I will fix it soon

**Comment by AbirHasan2005** [comment]
@Venomhash123
Will you test with latest commit?

**Comment by rubandurai27** [comment]
![Screenshot_2021-12-01-20-37-25-371_org telegram plus](https://user-images.githubusercontent.com/77948100/144260606-489d172e-ae1c-4ab9-b7ed-a77ac1e94336.jpg)

**Comment by AbirHasan2005** [comment]
Check again please 😅
I forgot to edit one line 🙈

**Comment by rubandurai27** [comment]
[working](https://telegra.ph/file/8a043ca50658ca42bc824.jpg)

**Comment by rubandurai27** [comment]
![Screenshot_2021-12-02-06-32-54-920_org telegram plus](https://user-images.githubusercontent.com/77948100/144339051-8d45417c-55d2-47d0-9063-4f2008d03c81.jpg)

**Comment by AbirHasan2005** [comment]
Any other problem found in bot?
