### ISSUE TITLE
Pyromgram

### ISSUE THREAD

**Issue by itzmadara** [AbirHasan2005/Rename-Bot#28]
Please Update Pyrogram Version

**Comment by Venomhash123** [comment]
Ya please update pyrogram version
'Client time has to be synchronized' this problem occured

**Comment by itzmadara** [comment]
> Ya please update pyrogram version 'Client time has to be synchronized' this problem occured



> Ya please update pyrogram version 'Client time has to be synchronized' this problem occured

Traceback (most recent call last):
2024-01-19T09:57:06.050498+00:00 app[worker.1]:   File "<frozen runpy>", line 189, in _run_module_as_main
2024-01-19T09:57:06.050498+00:00 app[worker.1]:   File "<frozen runpy>", line 148, in _get_module_details
2024-01-19T09:57:06.050498+00:00 app[worker.1]:   File "<frozen runpy>", line 112, in _get_module_details
2024-01-19T09:57:06.050502+00:00 app[worker.1]:   File "/app/bot/__init__.py", line 4, in <module>
2024-01-19T09:57:06.050601+00:00 app[worker.1]:     import bot.client
2024-01-19T09:57:06.050623+00:00 app[worker.1]:   File "/app/bot/client.py", line 8, in <module>
2024-01-19T09:57:06.050689+00:00 app[worker.1]:     from bot.core.new import New
2024-01-19T09:57:06.050710+00:00 app[worker.1]:   File "/app/bot/core/new/__init__.py", line 3, in <module>
2024-01-19T09:57:06.050761+00:00 app[worker.1]:     from .normal_rename import NormalRename
2024-01-19T09:57:06.051997+00:00 app[worker.1]:   File "/app/bot/core/new/normal_rename.py", line 17, in <module>
2024-01-19T09:57:06.051998+00:00 app[worker.1]:     from pyrogram.scaffold import Scaffold
2024-01-19T09:57:06.051998+00:00 app[worker.1]: ModuleNotFoundError: No module named 'pyrogram.scaffold'

When I updated  Pyrogram==2.0.106 I got this Eror in Hroku

**Comment by itzmadara** [comment]
![Screenshot_20240119_152918](https://github.com/AbirHasan2005/Rename-Bot/assets/141416632/030346f8-347c-4915-a78c-88e8ca756bed)
